#!/bin/sh
name="ldconfig"
ldconfig_command="/sbin/ldconfig"

err () {
	exitval=$1
	shift
	echo "$*"
	exit $exitval
}

init_ruby_path()
{
	FIND_PATH="${DIR}/lib/ruby"

	[ ! -d "${FIND_PATH}" ] && err 1 "Unable to find ${FIND_PATH}"

	RUBY_DIR=$( find ${FIND_PATH}/*.*/ -type f -name json.rb -depth 1 -maxdepth 1 -exec dirname {} \; 2>/dev/null )

	[ -z "${RUBY_DIR}" ] && err 1 "Unable to locate json.rb"
	RUBY_PLATFORM_DIR=$( find ${RUBY_DIR}/*-freebsd*/ -type f -name rbconfig.rb -depth 1 -maxdepth 1 -exec dirname {} \; )

	[ -z "${RUBY_PLATFORM_DIR}" ] && err 1 "Unable to locate rbconfig.rb"

	RUBY_VER=$( basename ${RUBY_DIR} )

	[ -z "${RUBY_VER}" ] && err 1 "Unable to determine ruby ver by dir path"
}

ldconfig_start()
{
	local _files _ins

	_ins=
	ldconfig=${ldconfig_command}
	if [ -x "${ldconfig_command}" ]; then
		_LDC="/lib /usr/lib"
		for i in ${ldconfig_local_dirs}; do
			if [ -d "${i}" ]; then
				_files=$( find ${i} -type f )
				if [ -n "${_files}" ]; then
					ldconfig_paths="${ldconfig_paths} `cat ${_files} | sort -u`"
				fi
			fi
		done
		for i in ${ldconfig_paths} /etc/ld-elf.so.conf; do
			if [ -r "${i}" ]; then
				_LDC="${_LDC} ${i}"
			fi
		done
		${ldconfig} -elf ${_ins} ${_LDC}
	fi
}

pkg install -y sysutils/puppet4
# run it twice
/usr/local/bin/puppet apply --hiera_config /usr/local/etc/puppet/hiera.yaml --color false --modulepath=/usr/local/etc/puppet/modules $@
/usr/local/bin/puppet apply --hiera_config /usr/local/etc/puppet/hiera.yaml --color false --modulepath=/usr/local/etc/puppet/modules $@
